### ISSUE TITLE
Audio fragment can guarantee a crash if loading audio fails

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1341]
In cases when audio fails, leaving an exploration will trigger a crash. This can be reproed by getting the app into a bad state similar to https://github.com/oppia/oppia-android/issues/1340 (e.g. disabling internet connectivity and then navigating back from the exploration player). The following crash occurs:

```
2020-06-17 12:29:45.755 22593-22593/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 22593
    java.lang.RuntimeException: Unable to stop activity {org.oppia.app/org.oppia.app.player.exploration.ExplorationActivity}: java.lang.IllegalStateException: Media Player not in a prepared state
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4624)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Media Player not in a prepared state
        at org.oppia.domain.audio.AudioPlayerController.pause(AudioPlayerController.kt:214)
        at org.oppia.app.player.audio.AudioViewModel.pauseAudio(AudioViewModel.kt:119)
        at org.oppia.app.player.audio.AudioFragmentPresenter.handleOnStop(AudioFragmentPresenter.kt:161)
        at org.oppia.app.player.audio.AudioFragment.onStop(AudioFragment.kt:57)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2891)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2884)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2884)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
2020-06-17 12:29:45.755 22593-22593/org.oppia.app E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1473)
        at android.app.Activity.performStop(Activity.java:8018)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616)
        	... 13 more
```

**Comment by anandwana001** [comment]
This error is not arising with the latest develop branch.

**Comment by BenHenning** [comment]
I just this locally by entering an exploration, playing audio, turning off wifi, navigating to the next state, observing that audio tries to play but doesn't, then navigating back to the story page & back to the exploration, then back to the story page & waiting about a minute. Not sure if all of these steps are needed, but I did observe a similar crash:

```
    Process: org.oppia.app, PID: 17368
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.oppia.domain.audio.AudioPlayerController$AudioPlayerException: Audio Player put in error state with what: 1 and extra: -2147483648
        at org.oppia.domain.audio.AudioPlayerController$setMediaPlayerListeners$3.onError(AudioPlayerController.kt:142)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3440)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by BenHenning** [comment]
I noticed one thing when investigating ``AudioPlayerControllerTest`` locally--it seems in a test environment if you call play too soon after initializeMediaPlayer (e.g.before it completes), that can result in this issue. I think AudioPlayerController's API needs to be made to be robust against timing sensitivity when interacting with playing audio tracks.

**Comment by BenHenning** [comment]
The robustness work above is probably true, but my focus here is to make sure the user-facing crash isn't possible. This issue is happening because AudioFragmentPresenter tries to pause audio when you play without internet connectivity. It only fails if #1340 or similar happens (audio player is in a bad state).
