### ISSUE TITLE
Media player has not been previously initialized

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1511]
**Describe the bug**
After changing text size from exploration in options, coming back to the Topic screen will cause the crash while putting MediaPlayer in the end state. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Fraction Exploration
2. Start lesson `What is Fraction?`
3. Click on Overflow Menu -> Options -> Change text size to any value -> Press Back
4. Leave the exploration by pressing back -> as soon as you arrived in the Topic screen, the app will crash.  

**Expected behaviour**
The app should not crash. User can easliy navigate between exploration -> options -> exploration -> topic 

**Device**
- Pixel XL
- 28 API

**Error**
<pre>
2020-07-23 14:32:13.567 13867-13867/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 13867
    java.lang.RuntimeException: Unable to destroy activity {org.oppia.app/org.oppia.app.player.exploration.ExplorationActivity}: java.lang.IllegalStateException: Media player has not been previously initialized
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4458)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4476)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     <b>Caused by: java.lang.IllegalStateException: Media player has not been previously initialized
        at org.oppia.domain.audio.AudioPlayerController.releaseMediaPlayer(AudioPlayerController.kt:264)
        at org.oppia.app.player.audio.AudioViewModel.handleRelease(AudioViewModel.kt:127)
        at org.oppia.app.player.audio.AudioFragmentPresenter.handleOnDestroy(AudioFragmentPresenter.kt:177)
        at org.oppia.app.player.audio.AudioFragment.onDestroy(AudioFragment.kt:67)</b>
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2924)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:458)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2843)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2919)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:458)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2843)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2919)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:458)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2843)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at android.app.Activity.performDestroy(Activity.java:7395)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
2020-07-23 14:32:13.567 13867-13867/org.oppia.app E/AndroidRuntime:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4443)
        	... 11 more
</pre>

**Additional Context**
After debugging I found that with the above mention flow exploration -> options -> change text size -> exploration -> topic, the onDestroy of `AudioFragment` is calling twice which can be the possible reason of this crash.

**Comment by anandwana001** [comment]
I tried this again with the latest develop branch and this crash is not coming. Putting this comment as a reference to check before alpha release.

**Comment by BenHenning** [comment]
Related issue: https://github.com/oppia/oppia-android/issues/1341

**Comment by anandwana001** [comment]
Similar issues found. 
Closing this one.
