### ISSUE TITLE
App crashes for some interactions on Huawei CAM-L21

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1513]
**Describe the bug**
App crashes for some interactions in my real device because of something related to the HtmlParser

**To Reproduce**
1. Go to 'Fractions Topic/Lessons'
2. Expand the Story 'Mathew Goes to the Bakery'
3. Click on the first chapter 'What is Fraction?'

**Another Steps**
1. Go to 'First Test Topic/Lessons'
2. Expand the first story
3. Click the first chapter 'Prototype Exploration'
4. Play the exploration till you face an error after the RGB question

**Error Log**
```
java.lang.RuntimeException: PARAGRAPH span must end at paragraph boundary
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:693)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:668)
        at android.text.HtmlToSpannedConverter.convert(Html.java:480)
        at android.text.Html.fromHtml(Html.java:136)
        at androidx.core.text.HtmlCompat.fromHtml(HtmlCompat.java:165)
        at org.oppia.util.parser.HtmlParser.parseOppiaHtml(HtmlParser.kt:58)
        at org.oppia.app.player.state.StatePlayerRecyclerViewAssembler$Builder$addContentSupport$2.invoke(StatePlayerRecyclerViewAssembler.kt:687)
        at org.oppia.app.player.state.StatePlayerRecyclerViewAssembler$Builder$addContentSupport$2.invoke(StatePlayerRecyclerViewAssembler.kt:642)
        at org.oppia.app.recyclerview.BindableAdapter$MultiTypeBuilder$registerViewBinder$viewHolderFactory$1$1.bind$app_debug(BindableAdapter.kt:242)
        at org.oppia.app.recyclerview.BindableAdapter.onBindViewHolder(BindableAdapter.kt:86)
        at org.oppia.app.recyclerview.BindableAdapter.onBindViewHolder(BindableAdapter.kt:30)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16772)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
        at android.view.View.layout(View.java:16772)
    	at android.view
```

**Device**
- Huawei Y6 II (CAM-L21)
- Android 6.0 (API 23)

**Comment by anandwana001** [comment]
I think it's because `HtmlCompat.fromHtml` method arrives in API 24 and we running in lower level. Is that so?

Similar - https://github.com/wordpress-mobile/AztecEditor-Android/pull/539/files

**Comment by MohamedMedhat1998** [comment]
> 
> 
> I think it's because `HtmlCompat.fromHtml` method arrives in API 24 and we running in lower level. Is that so?
> 
> Similar - https://github.com/wordpress-mobile/AztecEditor-Android/pull/539/files

I have no idea, I think we should ping someone who worked on the parser before

**Comment by BenHenning** [comment]
Is this a regression or has it been broken like this since that code was introduced?

**Comment by BenHenning** [comment]
Are we sure this is a compatibility issue? HtmlCompat is part of AndroidX so it doesn't have SDK minimums.

**Comment by MohamedMedhat1998** [comment]
> Is this a regression or has it been broken like this since that code was introduced?

This has been happening the first day I installed the app on my device

> Are we sure this is a compatibility issue? HtmlCompat is part of AndroidX so it doesn't have SDK minimums.

@BenHenning I'm not sure whether it is a device-specific problem or android API level-specific problem
