### ISSUE TITLE
Options-multipane screen "FragmentManager has been destroyed" error

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1559]
**Describe the bug**
The options screen in tablet devices crashes when you rotate a screen and try to click on some item of the Left-Hand side options

**To Reproduce**
1. Checkout this PR #1558 
2. Open a tablet emulator
3. Navigate to Home/NavigationDrawer/Options
4. Rotate the screen
5. Click on some items on the left (e.g. App Language)
6. see the error
```
java.lang.IllegalStateException: FragmentManager has been destroyed
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1911)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1942)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at org.oppia.app.options.OptionsActivityPresenter.loadAppLanguageFragment(OptionsActivityPresenter.kt:89)
        at org.oppia.app.options.OptionsActivity.loadAppLanguageFragment(OptionsActivity.kt:107)
        at org.oppia.app.options.OptionsAppLanguageViewModel.loadAppLanguageFragment(OptionsAppLanguageViewModel.kt:17)
        at org.oppia.app.options.OptionsAppLanguageViewModel.onAppLanguageClicked(OptionsAppLanguageViewModel.kt:22)
        at org.oppia.app.databinding.OptionAppLanguageBindingImpl._internalCallbackOnClick(OptionAppLanguageBindingImpl.java:167)
        at org.oppia.app.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Expected behavior**
The app should replace the fragment on the right-hand side with the correct fragment as it does before rotating the screen

**Device**
- Emulator: Google Pixel C (tablet)
- API Level: 25

**Additional context**
This code isn't in the develop branch yet. It is in a draft PR.

**Comment by MohamedMedhat1998** [comment]
Closing this PR because it wasn't in the develop
