### ISSUE TITLE
Drag & drop interaction is broken

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1626]
**Describe the bug**
When snapping together items in drag & drop, the items disappear.

**To Reproduce**
1. Open app
2. Open prototype exploration
3. Play through to the second drag & drop interaction
4. Click on the combine button to combine two elements
5. See the items disappear.

**Expected behavior**
Items should snap together, not disappear.

**Screen recording**
![broken_drag_drop_merge](https://user-images.githubusercontent.com/12983742/89978280-08089380-dc22-11ea-91af-7ce62861b00a.gif)

**Device**
- Device: Pixel XL
- SDK version: 29

**Additional context**
This was reproed on an app build with the latest develop (553200914d84fd2a0830f24ef9ffe5b69122f6ee).

**Comment by BenHenning** [comment]
Also: I noticed this when running StateFragmentTest--it correctly catches this issue.

**Comment by BenHenning** [comment]
Seems to be caused by 553200914d84fd2a0830f24ef9ffe5b69122f6ee. This does not repro in d210f388a0e8c0dcd6511efc29d584ce81ffb456.

/cc @anandwana001

**Comment by anandwana001** [comment]
@rt4914 

```
 Process: org.oppia.app, PID: 29591
    java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling org.oppia.app.player.state.DragDropSortInteractionView{bf02918 VFED..... ......ID 0,94-1216,1070 #7f0900ef app:id/drag_drop_interaction_recycler_view}, adapter:org.oppia.app.recyclerview.BindableAdapter@256ff71, layout:androidx.recyclerview.widget.LinearLayoutManager@3456156, context:org.oppia.app.player.exploration.ExplorationActivity@97bd862
        at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3051)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5536)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
        at org.oppia.app.recyclerview.BindableAdapter.setData(BindableAdapter.kt:45)
        at org.oppia.app.recyclerview.BindableAdapter.setDataUnchecked(BindableAdapter.kt:68)
        at org.oppia.app.player.state.itemviewmodel.DragAndDropSortInteractionViewModel.onDragEnded(DragAndDropSortInteractionViewModel.kt:74)
        at org.oppia.app.databinding.DragDropInteractionItemBindingImpl._internalCallbackOnDragEnded(DragDropInteractionItemBindingImpl.java:277)
        at org.oppia.app.generated.callback.OnDragEndedListener.onDragEnded(OnDragEndedListener.java:11)
        at org.oppia.app.recyclerview.DragAndDropItemFacilitator.clearView(DragAndDropItemFacilitator.kt:38)
```
