### ISSUE TITLE
AdministratorControl orientation change bug

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1676]
**Describe the bug**
App crash on Administrator screen when the screen rotates.

**Possible cause**
Null fragment reference in AdministratorControlsAccountActionsViewModel after orientation changes

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Administrator control screen
2. Click on logout -> see dialog appears -> click on cancel
3. rotate the screen -> click on logout -> app crash

**Expected behaviour**
Dialog should appear

**Error**
```
2020-08-19 12:58:02.702 1522-1522/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 1522
    kotlin.KotlinNullPointerException
        at org.oppia.app.administratorcontrols.administratorcontrolsitemviewmodel.AdministratorControlsAccountActionsViewModel.onLogOutClicked(AdministratorControlsAccountActionsViewModel.kt:15)
        at org.oppia.app.databinding.AdministratorControlsAccountActionsViewBindingLandImpl._internalCallbackOnClick(AdministratorControlsAccountActionsViewBindingLandImpl.java:134)
        at org.oppia.app.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by anandwana001** [comment]
We also need to check `WalkthroughTopicViewModel`
