### ISSUE TITLE
Double click on adminControl in nav crash

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1866]
**Describe the bug**
AdministratorControls in the menu gets crash when double click

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home
2. Open navigation drawer
3. Click on AdministratorControls -> nav will get close 
4. Click on AdministratorControls again and see the crash

**Expected behavior**
Should close the nav smoothly

**Error**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 14166
    java.lang.IllegalArgumentException: NavigationDrawerItem not found by 0
        at org.oppia.app.drawer.NavigationDrawerItem$Companion.valueFromNavId(NavigationDrawerItem.kt:20)
        at org.oppia.app.drawer.NavigationDrawerFragmentPresenter$subscribeToProfileLiveData$1$1.onClick(NavigationDrawerFragmentPresenter.kt:115)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by BenHenning** [comment]
@anandwana001 @Sarthak2601 @MohamedMedhat1998 is this actually part of SLoP? If not, can #1867 be reopened & continued? Otherwise, that could be used as a starting point for this issue that might make it easier & a potential "second issue."

**Comment by Sarthak2601** [comment]
@BenHenning Yes, I think #1867 can be reopened and continued. It's basically the reason why we removed it from SLoP.

**Comment by anandwana001** [comment]
> @BenHenning Yes, I think #1867 can be reopened and continued. It's basically the reason why we removed it from SLoP.

Cool, I will open it back.

**Comment by BenHenning** [comment]
Thanks for confirming! @anandwana001 re-assigning to you since the PR was reopened.

**Comment by MaskedCarrot** [comment]
@anandwana001  is this issue still available to work on?

**Comment by anandwana001** [comment]
This is a duplicate issue. Thanks for bringing this into attention.
