### ISSUE TITLE
Exploration crashes for wrong answer in StateFragment

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2298]
**Describe the bug**
`E/StateFragment: Failed to retrieve answer outcome` for wrong answer in Exploration

**To Reproduce**
1. Go to 'Prototype Exploration` in First Test Topic
2. Answer all question till the question 'What is 11 times 11'
3. Answer it incorrect 
4. See error in the logcat and submit button doesn't respond

**Expected behavior**
Add a msg for wrong and

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Device**
- Pixel 3A XL (emulator)
- SDK version 27

**Additional context**
*Crash message*
```
org.oppia.android E/RecyclerView: No adapter attached; skipping layout
org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    java.lang.IllegalStateException: Expected interaction NumericInput to have classifier for rule type: isLessThan, but only has: [Equals, IsGreaterThanOrEqualTo, IsGreaterThan, IsInclusivelyBetween, IsLessThanOrEqualTo, IsLessThan, IsWithinTolerance]
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:54)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:33)
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswer(ExplorationProgressController.kt:144)
        at org.oppia.android.app.player.state.StateFragmentPresenter.handleSubmitAnswer(StateFragmentPresenter.kt:459)
        at org.oppia.android.app.player.state.StateFragmentPresenter.onSubmitButtonClicked(StateFragmentPresenter.kt:181)
        at org.oppia.android.app.player.state.StateFragment.onSubmitButtonClicked(StateFragment.kt:102)
        at org.oppia.android.databinding.SubmitButtonItemBindingImpl._internalCallbackOnClick(SubmitButtonItemBindingImpl.java:324)
        at org.oppia.android.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by FareesHussain** [comment]
@rt4914, @anandwana001 please check if you can reproduce this

Also I'm not sure why there is a crash for this.
Can I know where these questions are stored

**Comment by BenHenning** [comment]
Aha, this is a great finding. It appears there's a casing issue here: https://github.com/oppia/oppia-android/blob/141511329ea0249ff225a469c70658c3b2123238/domain/src/main/assets/test_exp_id_2.json#L393 should be "IsLessThan". It's only caught because you inputted something less than 121, and I guess no one has done that before. :)

I'm also thinking about whether we should test this, but given it's an issue with the prototype exploration I'm inclined not to. It might be worth adding validation to the JSON parser, though, and have a pathway to fail loading the exploration if the classifiers don't match the expected ones for the given interaction (and subsequently if the interaction doesn't match the ones supported by the app). I think adding functionality for these cases & tests may be worthwhile--this failure should be triggered for the prototype exploration before it's fixed.

**Comment by FareesHussain** [comment]
@BenHenning it gives the same error for greater than 121 too
![image](https://user-images.githubusercontent.com/54740946/102912987-1f933b00-44a4-11eb-900a-3fde337ddfbc.png)

**Comment by BenHenning** [comment]
Thanks for clarifying @FareesHussain. It seems a few of the classifiers are wrong in that file. Going to try and get a PR out later tonight to fix.
