### ISSUE TITLE
Fix test testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish

### ISSUE THREAD

**Issue by yurilev** [oppia/oppia-android#2588]
Fails in CI Robolectric Tests - App Module:
```
org.oppia.android.app.player.exploration.ExplorationActivityTest > testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish FAILED
    androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.oppia.android:id/continue_button'.
        at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
        at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
        at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
        at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
        at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
        at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
        at org.oppia.android.app.player.exploration.ExplorationActivityTest.testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish(ExplorationActivityTest.kt:580)

        Caused by:
        java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
        at least 90 percent of the view's area is displayed to the user.
        Target view: "AppCompatButton{id=2131296485, res-name=continue_button, visibility=VISIBLE, width=264, height=144, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2c050232, tag=null, root-is-layout-requested=false, has-input-connection=false, x=504.0, y=48.0, text=Continue, input-type=0, ime-target=false, has-links=false}"
            at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:252)
            at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
            at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
            at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:873)
            at android.os.Handler.handleCallback(Handler.java)
            at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
            at android.os.Handler.dispatchMessage(Handler.java)
            at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:308)
            at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:273)
            at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:85)
            at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:15)
            at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:318)
            ... 3 more
```

**Comment by yurilev** [comment]
See https://github.com/oppia/oppia-android/pull/2586/checks?check_run_id=1798360773

**Comment by yurilev** [comment]
Note: Passes locally (Robolectric and in an emulator).

**Comment by janewaitara** [comment]
@yurilev  I am also having the same issue with the pull requests I'm working on

**Comment by yurilev** [comment]
I synced my branch and ran again today, and the test passed.

@janewaitara Please reopen if it's still happening for you, the test might be flaky.
