### ISSUE TITLE
App crashes when trying to run on Android 4.4 KitKat (SDK 19)

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#3504]
**Describe the bug**
App crashes on "Select your profile" screen when choosing Admin.

**To Reproduce**
1. Open the app
2. On the screen where prompted to choose the profile select "Admin"
3. See error

**Expected behavior**
The app should continue working properly leading to the Home screen

**Screenshots**
![image](https://user-images.githubusercontent.com/76056229/126206554-06d58c1d-006e-458a-bd7f-656bd2dc963a.png)
![image](https://user-images.githubusercontent.com/76056229/126206591-a53f58d4-7233-48fa-9456-1cadfb91675d.png)

**Device**

Name: Pixel_API_19
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 19)
SD Card: 512 MB
hw.ramSize: 1500
hw.cpu.ncore: 4
vm.heapSize: 228
hw.device.manufacturer: Google
disk.dataPartition.size: 800M

**Error Log**
07-21 00:46:37.700 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'androidx.work.impl.background.systemjob.SystemJobService', referenced from method androidx.work.impl.Schedulers.createBestAvailableBackgroundScheduler
07-21 00:46:37.700 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateCallback', referenced from method androidx.work.impl.constraints.trackers.NetworkStateTracker.<init>
07-21 00:46:37.800 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'androidx.core.view.ViewCompat$2', referenced from method androidx.core.view.ViewCompat.addOnUnhandledKeyEventListener
07-21 00:46:37.800 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.view.View$OnUnhandledKeyEventListener', referenced from method androidx.core.view.ViewCompat.removeOnUnhandledKeyEventListener
07-21 00:46:37.810 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'androidx.core.view.ViewCompat$1', referenced from method androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener
07-21 00:46:37.890 6232-6232/org.oppia.android E/EGL_emulation: tid 6232: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
07-21 00:46:38.000 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'java.util.Optional', referenced from method org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get
07-21 00:46:38.020 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method androidx.appcompat.widget.AppCompatImageHelper.hasOverlappingRendering
07-21 00:46:38.020 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.view.textclassifier.TextClassificationManager', referenced from method androidx.appcompat.widget.AppCompatTextClassifierHelper.getTextClassifier
07-21 00:46:38.070 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'de.hdodenhof.circleimageview.CircleImageView$OutlineProvider', referenced from method de.hdodenhof.circleimageview.CircleImageView.init
07-21 00:46:38.170 6232-6232/org.oppia.android E/EGL_emulation: tid 6232: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
07-21 00:47:32.132 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'androidx.drawerlayout.widget.DrawerLayout$1', referenced from method androidx.drawerlayout.widget.DrawerLayout.<init>
07-21 00:47:32.132 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.drawerlayout.widget.DrawerLayout.onDraw
07-21 00:47:32.132 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.drawerlayout.widget.DrawerLayout.onMeasure
07-21 00:47:32.152 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.drawerlayout.widget.DrawerLayout.onMeasure
07-21 00:47:32.172 6232-6232/org.oppia.android E/dalvikvm: Could not find class 'org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter$setIfDeveloperOptionsMenuItemListener$1', referenced from method org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter.setIfDeveloperOptionsMenuItemListener
07-21 00:47:32.312 6232-6232/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 6232
    java.lang.NoClassDefFoundError: java.util.Optional
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1542)
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1534)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:59)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:15)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.injectNavigationDrawerFragment(DaggerApplicationComponent.java:3279)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.inject(DaggerApplicationComponent.java:3020)
        at org.oppia.android.app.drawer.NavigationDrawerFragment.onAttach(NavigationDrawerFragment.kt:24)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2669)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:229)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1215)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at org.oppia.android.app.home.HomeActivityPresenter.handleOnCreate(HomeActivityPresenter.kt:20)
        at org.oppia.android.app.home.HomeActivity.onCreate(HomeActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by rt4914** [comment]
@ayush0402 can you please add error log also to the description so that we can understand the error ?

**Comment by ayush0402** [comment]
@rt4914 Added the error log.

**Comment by rt4914** [comment]
Thanks @ayush0402

**Comment by rt4914** [comment]
Test this on API 24 and 25 aloso.

**Comment by ayush0402** [comment]
@rt4914 No issues with API 24 and 25.

**Comment by rt4914** [comment]
Duplicate #3669
