### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#3669]
**Describe the bug**
The app crashes when I press on a profile to reach the main screen.

**To Reproduce**
1. Navigate to the profile chooser screen.
2. Choose any profile.
3. App crashes.

**Expected behavior**
The app opens the home screen normally.

**Device**
- Huawei Y6 II (Cam L21)
- API level 23

**Full Log**
```
FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 28847
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1577)
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1569)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:59)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:15)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.injectNavigationDrawerFragment(DaggerApplicationComponent.java:3436)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.inject(DaggerApplicationComponent.java:3160)
        at org.oppia.android.app.drawer.NavigationDrawerFragment.onAttach(NavigationDrawerFragment.kt:24)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2669)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:229)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1215)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at org.oppia.android.app.home.HomeActivityPresenter.handleOnCreate(HomeActivityPresenter.kt:20)
        at org.oppia.android.app.home.HomeActivity.onCreate(HomeActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:6372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
        at android.app.ActivityThread.access$900(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5659)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/org.oppia.android-1/base.apk"],nativeLibraryDirectories=[/data/app/org.oppia.android-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1577) 
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1569) 
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:59) 
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:15) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.injectNavigationDrawerFragment(DaggerApplicationComponent.java:3436) 
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.inject(DaggerApplicationComponent.java:3160) 
        at org.oppia.android.app.drawer.NavigationDrawerFragment.onAttach(NavigationDrawerFragment.kt:24) 
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2669) 
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:229) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1215) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398) 
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109) 
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135) 
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356) 
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:862) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:537) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:437) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170) 
        at org.oppia.android.app.home.HomeActivityPresenter.handleOnCreate(HomeActivityPresenter.kt:20) 
        at org.oppia.android.app.home.HomeActivity.onCreate(HomeActivity.kt:39) 
        at android.app.Activity.performCreate(Activity.java:6372) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
        at android.app.ActivityThread.access$900(ActivityThread.java:168) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5659) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
    	Suppressed: java.lang.ClassNotFoundException: java.util.Optional
    		at java.lang.Class.classForName
```

**Comment by MohamedMedhat1998** [comment]
@rt4914

**Comment by rt4914** [comment]
Yeah this needs to be fixed. @MohamedMedhat1998 Are you working on it?

**Comment by MohamedMedhat1998** [comment]
> Yeah this needs to be fixed. @MohamedMedhat1998 Are you working on it?

Unfortunately no. I just faced this issue while using the app for translation checking so I reported it.
