### ISSUE TITLE
Espresso test failing at PinPasswordActivityTest [Blocked on #3684]

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#3771]
**Describe the bug**
<code>testPinPassword_withUser_forgot_inputAdminPinAndNullPin_imeAction_errorIsDisplayed</code> espresso test is failing in PinPasswordActivityTest.kt
(app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt)

**Screenshots**
![132320590-c343e6a9-86ed-4313-a9f0-150b6eed080e](https://user-images.githubusercontent.com/76056229/132462256-2671942a-3dad-4044-93d3-271bce5e30e5.png)

**Device**
- Pixel 3a
- API 28

**Error Log**
```
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'The expected error text is 'Please enter Administrator PIN.'' doesn't match the selected view.
Expected: The expected error text is 'Please enter Administrator PIN.'
Got: "TextInputLayout{id=2131296365, res-name=admin_settings_input_pin, visibility=VISIBLE, width=804, height=200, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@164e01, tag=null, root-is-layout-requested=false, has-input-connection=false, x=66.0, y=88.0, child-count=2}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:324)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.oppia.android.app.profile.PinPasswordActivityTest.testPinPassword_withUser_forgot_inputAdminPinAndNullPin_imeAction_errorIsDisplayed(PinPasswordActivityTest.kt:800)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: 'The expected error text is 'Please enter Administrator PIN.'' doesn't match the selected view.
Expected: The expected error text is 'Please enter Administrator PIN.'
Got: "TextInputLayout{id=2131296365, res-name=admin_settings_input_pin, visibility=VISIBLE, width=804, height=200, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@164e01, tag=null, root-is-layout-requested=false, has-input-connection=false, x=66.0, y=88.0, child-count=2}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:540)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:105)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:425)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:288)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by yash10019coder** [comment]
It is blocked as the ui is changed completely due to the PR [link for the PR](https://github.com/oppia/oppia-android/pull/3684) therefore the test cases will change therefore it is of no need to do it until this PR is merged

**Comment by yash10019coder** [comment]
Hi @ayush0402 I think that this test now passes successfully so we can close this issue
![image](https://user-images.githubusercontent.com/76404817/143926430-6b629ce9-4372-45e4-9bb0-ae2a7a479f3f.png)

**Comment by yash10019coder** [comment]
closing this issue as this is now passing
