### ISSUE TITLE
Failed to retrieve oldest saved checkpoint details.

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3779]
**Describe the bug**
Getting error log when opening exploration for the first time. 

**To Reproduce**
1. Go to lesson tab
2. Start any explortaion
3. Check logcat

**Expected behavior**
Investigate what the error is about and what is the suitable solution. 

**Device**
- Emulator being used - Pixel XL 
- SDK version 19 and 28

**Additional context**
```
09-13 10:10:48.272 E/ExplorationActivity: Failed to retrieve oldest saved checkpoint details.
    org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$ExplorationCheckpointNotFoundException: No saved checkpoints in exploration_checkpoint_database for profileId 0.
        at org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$retrieveOldestSavedExplorationCheckpointDetails$1.invokeSuspend(ExplorationCheckpointController.kt:207)
        at org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$retrieveOldestSavedExplorationCheckpointDetails$1.invoke(ExplorationCheckpointController.kt)
        at org.oppia.android.util.data.AsyncResult$transformAsync$2.invokeSuspend(AsyncResult.kt:90)
        at org.oppia.android.util.data.AsyncResult$transformAsync$2.invoke(AsyncResult.kt)
        at org.oppia.android.util.data.AsyncResult.transformWithResultAsync(AsyncResult.kt:147)
        at org.oppia.android.util.data.AsyncResult.transformAsync(AsyncResult.kt:89)
        at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1.retrieveData(DataProviders.kt:73)
        at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1$retrieveData$1.invokeSuspend(DataProviders.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by BenHenning** [comment]
Note that this is a "known/okay error" that we may want to revise to be less noisy.

/cc  @MaskedCarrot in case you have any thoughts

**Comment by MaskedCarrot** [comment]
One possible way to make this less noisy is to modify the proto to be something like this.
```
message CheckpointDatabaseDetails {
    oneOf checkpointDatabaseState {
         bool checkpointDatabaseIsEmpty = 1;
         OldestCheckpointDetalis oldestCheckpointDetails = 2;
    } 
}

message oldestCheckpointDetails  {
    string exploration_title = 1;
    string exploration_id  = 2;
}
```

In this case, we will not have to return a failed async result if no checkpoint is saved, so no error will be logged.

@BenHenning WDYT?

**Comment by BenHenning** [comment]
Taking this since I can easily address it as part of #4696 (since I'm changing related code, anyway).

I think we can just use default instance here, no need for the oneof (though we could certainly move to that in a binary compatible way in the future).
