### ISSUE TITLE
Bazel not support vector drawables

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3804]
**Describe the bug**
Currently, the Bazel-built APK doesn't support vector drawables. 
Bazel Issue - https://github.com/bazelbuild/bazel/issues/2197 

**To Reproduce**
1. Build APK using Bazel from https://github.com/oppia/oppia-android/pull/3740
2. Run APK on any device
3. App crash with the following error

Error 1 on Kitkat
```
org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 2071
    java.lang.RuntimeException: Unable to start service androidx.work.impl.background.systemalarm.SystemAlarmService@9d18da98 with Intent { act=ACTION_RESCHEDULE cmp=org.oppia.android/androidx.work.impl.background.systemalarm.SystemAlarmService (has extras) }: java.lang.SecurityException: Neither user 10076 nor current process has android.permission.WAKE_LOCK.
```

Solution 1 (Dangerous Solution)
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

Error 2
```
org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 2876
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.oppia.android/org.oppia.android.app.splash.SplashActivity}: android.content.res.Resources$NotFoundException: File res/drawable/splash_page.xml from drawable resource ID #0x7f080146
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/splash_page.xml from drawable resource ID #0x7f080146
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3042)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
        at androidx.appcompat.app.AppCompatDelegateImpl.x(SourceFile:7864)
        at androidx.appcompat.app.AppCompatDelegateImpl.c(SourceFile:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:170)
        at org.oppia.android.app.splash.a.a(SourceFile:34)
        at org.oppia.android.app.splash.SplashActivity.onCreate(SourceFile:17)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2097)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3042) 
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085) 
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678) 
        at androidx.appcompat.app.AppCompatDelegateImpl.x(SourceFile:7864) 
        at androidx.appcompat.app.AppCompatDelegateImpl.c(SourceFile:693) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:170) 
        at org.oppia.android.app.splash.a.a(SourceFile:34) 
        at org.oppia.android.app.splash.SplashActivity.onCreate(SourceFile:17) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Expected behavior**
Find an alternative solution to support our vector drawable. 

**Unsupported Files**

1. ic_add_profile.xml
2. ic_admin_settings_icon_black_24dp.xml
3. ic_admin_settings_icon_brown_24dp.xml
4. ic_admin_settings_icon_grey_24dp.xml
5. ic_arrow_back_black_24_dp.xml
6. ic_arrow_back_oppia_dark_blue_24dp.xml
7. ic_arrow_back_white_24dp.xml
8. ic_arrow_down_grey_24dp.xml
9. ic_arrow_drop_down_black_24dp.xml
10. ic_arrow_drop_up_black_24dp.xml
11. ic_arrow_forward_black_24dp.xml
12. ic_arrow_forward_oppia_dark_blue_24dp.xml
13. ic_arrow_right_alt_24dp.xml
14. ic_arrow_right_grey_24dp.xml
15. ic_arrow_up_black_24dp.xml
16. ic_audio_lang_24px.xml
17. ic_audio_streaming_off_24dp.xml
18. ic_audio_streaming_on_24dp.xml
19. ic_available_offline_icon_white_12dp.xml
20. ic_available_offline_primary_24dp.xml
21. ic_baseline_code_24.xml
22. ic_baseline_lock_24.xml
23. ic_check_24dp.xml
24. ic_check_box_checked.xml
25. ic_check_box_disabled.xml
26. ic_check_box_unchecked.xml
27. ic_check_circle_primary_24dp.xml
28. ic_check_primary.xml
29. ic_close_white_24dp.xml
30. ic_default_avatar.xml
31. ic_dot_yellow_24dp.xml
32. ic_edit_18.xml
33. ic_edit.xml
34. ic_file_download_primary_24dp.xml
35. ic_folder_open_24dp.xml
36. ic_help_grey_icon_24dp.xml
37. ic_hide_eye_icon.xml
38. ic_hint_bulb_white_24dp.xml
39. ic_home_icon_grey_24dp.xml
40. ic_info_icon_24dp.xml
41. ic_info_icon_gray_24dp.xml
42. ic_info_icon.xml
43. ic_keyboard_arrow_down_black_24dp.xml
44. ic_keyboard_arrow_up_black_24dp.xml
45. ic_landscape_onboarding_0_tablet.xml
46. ic_landscape_onboarding_0.xml
47. ic_landscape_onboarding_1_tablet.xml
48. ic_landscape_onboarding_1.xml
49. ic_landscape_onboarding_2_tablet.xml
50. ic_landscape_onboarding_2.xml
51. ic_landscape_onboarding_3_tablet.xml
52. ic_landscape_onboarding_3.xml
53. ic_language_icon_grey_24dp.xml
54. ic_lessons_icon_24dp.xml
55. ic_merge_icon_24.xml
56. ic_options_icon_grey_24dp.xml
57. ic_pause_circle_filled_white_24dp.xml
58. ic_pending_24dp.xml
59. ic_play_circle_filled_white_24dp.xml
60. ic_portrait_onboarding_0.xml
61. ic_portrait_onboarding_1.xml
62. ic_portrait_onboarding_2.xml
63. ic_portrait_onboarding_3.xml
64. ic_practice_icon_24dp.xml
65. ic_profile_exit.xml
66. ic_refresh_white_24dp.xml
67. ic_revision_icon_24dp.xml
68. ic_settings_grey_48dp.xml
69. ic_show_eye_icon.xml
70. ic_start_over_24dp.xml
71. ic_unlink_icon_24.xml
72. ic_upload_photo.xml
73. lesson_thumbnail_graphic_baker.xml
74. lesson_thumbnail_graphic_child_with_book.xml
75. lesson_thumbnail_graphic_child_with_cupcakes.xml
76. lesson_thumbnail_graphic_child_with_fractions_homework.xml
77. lesson_thumbnail_graphic_duck_and_chicken.xml
78. lesson_thumbnail_graphic_person_with_pie_chart.xml
79. splash_page.xml

**Comment by BenHenning** [comment]
Reminder to please add the error stack that you encountered @anandwana001.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
