### ISSUE TITLE
KitKat version of the app crashes when clicking on the 'Help' menu, and when reopening after app close

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3939]
See title.

Note that for the reopening, the app needs to be swiped away in recents to trigger the issue.

**Comment by BenHenning** [comment]
Also: crashes when reopening a profile after crash.

Edit: after opening a profile always (except the first open).

**Comment by BenHenning** [comment]
Actually, I'm not sure what's going on here. I can't seem to get the app to open anymore, so maybe something became unstable in the system itself.

**Comment by BenHenning** [comment]
A full reinstall fixed it, but even an emulator restart didn't. I have no clue what was happening there; will need to dig into it more.

**Comment by BenHenning** [comment]
Interestingly, this is tied to Delegates trying to access something not fully in the dex files:

```
2021-10-21 11:52:45.938 2743-2743/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 2743
    java.lang.NoClassDefFoundError: kotlin.LazyKt$WhenMappings
        at kotlin.LazyKt__LazyJVMKt.lazy(LazyJVM.kt:34)
        at kotlin.reflect.jvm.internal.KProperty1Impl.<init>(KProperty1Impl.kt:37)
        at kotlin.reflect.jvm.internal.KMutableProperty1Impl.<init>(KProperty1Impl.kt:49)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.mutableProperty1(ReflectionFactoryImpl.java:101)
        at kotlin.jvm.internal.Reflection.mutableProperty1(Reflection.java:107)
        at org.oppia.android.app.help.HelpActivity.<clinit>(HelpActivity_updated.kt)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter.openActivityByMenuItemId(NavigationDrawerFragmentPresenter_updated.kt:255)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter.onNavigationItemSelected(NavigationDrawerFragmentPresenter_updated.kt:493)
        at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:210)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

Per https://youtrack.jetbrains.com/issue/KT-17034 it seems Delegates uses KProperty internally, which might be problematic in terms of both dex code needed & reflection (though the latter would be more of a Proguard issue, and we haven't seen problems on alpha builds). Will try to replace the Delegates bit to see if that fixes the crash.

Edit: I checked all three dex files and it does seem like WhenMappings isn't being fully included in the Dex. This might actually be a bug with Bazel in how it computes the Dex files; there might be an incompatibility when trying to determine which classes to include that somehow breaks with the Delegates mechanism. Not entirely sure yet.

Edit 2: Aha. I'm still not sure why the alpha build works on my Nexus 5X device (which isn't KitKat) but doesn't on KitKat despite containing the same Dex files. Nevertheless, when comparing oppia_dev_kitkat.aab with oppia_dev.aab, it becomes clear that the <clinit> of LazyKt$WhenMappings is completely missing from the dex list for the KitKat build. This *might* be because I'm fragmenting up LazyKt in the main class dex list for KitKat (or at least, that's my best guess) which might cause some weirdness with how the dexer is deciding which classes/members to include.

**Comment by BenHenning** [comment]
Adding kotlin/LazyKt$WhenMappings.class to kitkat_main_dex_class_list.txt fixes the crash above, but leads to a new one:

```
2021-10-21 12:10:20.858 3063-3063/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 3063
    java.lang.NoClassDefFoundError: kotlin.LazyThreadSafetyMode
        at kotlin.LazyKt__LazyJVMKt.lazy(LazyJVM.kt:34)
        at kotlin.reflect.jvm.internal.KProperty1Impl.<init>(KProperty1Impl.kt:37)
        at kotlin.reflect.jvm.internal.KMutableProperty1Impl.<init>(KProperty1Impl.kt:49)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.mutableProperty1(ReflectionFactoryImpl.java:101)
        at kotlin.jvm.internal.Reflection.mutableProperty1(Reflection.java:107)
        at org.oppia.android.app.help.HelpActivity.<clinit>(HelpActivity_updated.kt)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter.openActivityByMenuItemId(NavigationDrawerFragmentPresenter_updated.kt:255)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter.onNavigationItemSelected(NavigationDrawerFragmentPresenter_updated.kt:493)
        at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:210)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

I wonder if this is a reflection thing...

Edit: Okay, something weird is going on here. LazyThreadSafetyMode has a placeholder in classes.dex, but the full definition in classes2.dex. I don't understand why the dexer is adding placeholders & I suspect it's the reason for the NoClassDefError.

**Comment by BenHenning** [comment]
https://issuetracker.google.com/issues/131100011 is another possibility, but it's hard for me to know if this is happening with the Kotlin functions. I'm actually quite uncomfortable with this dexing inconsistency, but I think if we can at least get the app working then it should be a good step in the right direction.

Replacing Delegates with a standard var seems to avoid the crash (and per https://youtrack.jetbrains.com/issue/KT-15284 we unfortunately can't use lateinit on primitive types).

I also confirmed that this help menu crash existed with #3910, I just missed it during development.

However, now I'm getting a consistent crash after reopening the app regardless of the above fix, and this time without a stack trace. Need to dig deeper to figure out what's going on. This also happens with #3910.

**Comment by BenHenning** [comment]
Interestingly, the crash from reopening seems to only occur if the app previous crashed. My current repro steps:
1. Open the app & navigate to home screen (fresh install)
2. Open developer menu & force a crash
3. After the app reopens (sometimes it will crash at this step), swipe away the app from recents & reopen
4. Navigate to the home screen
5. Experience crash (sometimes it doesn't happen)

Waiting a bit of time with the app closed & then reopening it seems to avoid the crash.

**Comment by BenHenning** [comment]
Ah, there is a stack trace but it's not sent to error logs. This is a native crash happening:

```
2021-10-21 13:04:51.148 5651-5697/org.oppia.android A/libc: invalid address or address of corrupt block 0xb913e218 passed to dlfree
2021-10-21 13:04:51.148 5651-5697/org.oppia.android A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 5697 (glide-source-th)
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: Build fingerprint: 'generic_x86/google_sdk_x86/generic_x86:4.4.2/KK/6761301:eng/test-keys'
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: Revision: '0'
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: pid: 5651, tid: 5697, name: glide-source-th  >>> org.oppia.android <<<
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
2021-10-21 13:04:51.258 1171-1171/? I/DEBUG: Abort message: 'invalid address or address of corrupt block 0xb913e218 passed to dlfree'
2021-10-21 13:04:51.348 1171-1171/? I/DEBUG:     eax baa12595  ebx b7764fcc  ecx 8d9e804b  edx baa12595
2021-10-21 13:04:51.348 1171-1171/? I/DEBUG:     esi b913e218  edi b913e220
2021-10-21 13:04:51.348 1171-1171/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
2021-10-21 13:04:51.348 1171-1171/? I/DEBUG:     eip b76dc774  ebp b9061740  esp 883008a0  flags 00210246
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG: backtrace:
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #00  pc 00013774  /system/lib/libc.so (dlfree+1940)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #01  pc 00013969  /system/lib/libc.so (dlrealloc+249)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #02  pc 0000d247  /system/lib/libc.so (realloc+39)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #03  pc 0025564a  /system/lib/libskia.so (sk_realloc_throw(void*, unsigned int)+42)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #04  pc 001360bb  /system/lib/libskia.so (SkPath::quadTo(float, float, float, float)+283)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #05  pc 000da9eb  /system/lib/libandroid_runtime.so (android::SkPathGlue::rQuadTo(_JNIEnv*, _jobject*, SkPath*, float, float, float, float)+75)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #06  pc 0002a0eb  /system/lib/libdvm.so (dvmPlatformInvoke+79)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #07  pc 000d68df  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #08  pc 0008688d  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+285)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #09  pc 0004c0d2  /system/lib/libdvm.so (dvmCheckCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+66)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #10  pc 00176c18  /system/lib/libdvm.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #11  pc 000034c7  <unknown>
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #12  pc 0003b582  /system/lib/libdvm.so (dvmMterpStd(Thread*)+66)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #13  pc 00036c49  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+217)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #14  pc 000bcba7  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, char*)+759)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #15  pc 000bcfb7  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+55)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #16  pc 00098f40  /system/lib/libdvm.so (interpThreadStart(void*)+992)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #17  pc 0000bc0c  /system/lib/libc.so (__thread_entry+236)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #18  pc 0003e075  /system/lib/libc.so (__pthread_clone+69)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #19  pc 00098b5f  /system/lib/libdvm.so (internalThreadStart(void*)+655)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG: stack:
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300860  b7769800  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300864  00000080  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300868  00000002  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830086c  baa12595  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300870  b7769800  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300874  00000110  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300878  b76e0249  /system/lib/libc.so (__libc_fatal(char const*, char*)+9)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830087c  b7764fcc  /system/lib/libc.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300880  b913e218  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300884  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300888  b9061740  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830088c  b76e06a1  /system/lib/libc.so (__libc_fatal_no_abort+17)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300890  b913e218  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300894  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300898  b9061740  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830089c  b76dc774  /system/lib/libc.so (dlfree+1940)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #00  883008a0  b774dae8  /system/lib/libc.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008a4  b913e218  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008a8  b774db63  /system/lib/libc.so (__FUNCTION__.4357)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008ac  88426000  [anon:libc_malloc]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008b0  00000000  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008b4  00000003  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008b8  88426000  [anon:libc_malloc]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008bc  b7764fcc  /system/lib/libc.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008c0  b90b1bc0  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008c4  b9176100  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008c8  b76dbfe9  /system/lib/libc.so (dlfree+9)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008cc  b7764fcc  /system/lib/libc.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008d0  0000010c  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008d4  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008d8  b9061740  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008dc  b76dc96a  /system/lib/libc.so (dlrealloc+250)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #01  883008e0  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008e4  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008e8  0000010c  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008ec  b76c59ec  /system/lib/libstdc++.so (operator delete(void*)+28)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008f0  b90b1bc0  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008f4  00000000  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008f8  b902b000  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          883008fc  b913e218  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300900  00000000  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300904  b76c59d6  /system/lib/libstdc++.so (operator delete(void*)+6)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300908  b7111c0c  /system/lib/libskia.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830090c  b7764fcc  /system/lib/libc.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300910  00000200  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300914  b9176100  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300918  00000200  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830091c  b76d6248  /system/lib/libc.so (realloc+40)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     #02  88300920  b913e220  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300924  00000200  
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300928  b902b000  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830092c  b6ded6b1  /system/lib/libskia.so (SkPathRef::makeSpace(unsigned int)+33)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300930  b90b1bc0  [heap]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300934  b76d6226  /system/lib/libc.so (realloc+6)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          88300938  b7111c0c  /system/lib/libskia.so
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:          8830093c  b6f0f64b  /system/lib/libskia.so (sk_realloc_throw(void*, unsigned int)+43)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG: memory map around fault addr deadbaad:
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     bf7eb000-bf80c000 rw- [stack]
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     (no map for address)
2021-10-21 13:04:51.358 1171-1171/? I/DEBUG:     (no map above)
```

**Comment by BenHenning** [comment]
Looks like a different repro for #3887 which is a known issue. The sometimes-crash-on-restart is definitely not good, but it seems to generally go away after a bit.

**Comment by BenHenning** [comment]
The crash doesn't seem to repro when using production assets, so I strongly suspect this second crash is exactly #3887.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
