### ISSUE TITLE
Unable to complete the topic Addition & Subtraction, as chapter 4 is getting crashed while trying to complete it

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4319]
**Describe the bug**
Unable to complete the topic Addition & Subtraction, as chapter 4 is getting crashed while trying to complete it

**To Reproduce**
1. Login as Admin
2. Go to 'Addition & Subtraction
3. Complete chapters 1,2,3
4. Try to complete chapter 4

**Expected behavior**
Admin should be able to complete chapter 4 to proceed further and complete the topic

Actual Result: 
While trying to complete chapter 4, it is getting auto closed and unable to complete the chapter. Hence unable to proceed further to complete other chapters

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

https://user-images.githubusercontent.com/101634267/165261038-f8bc7676-2f4b-4138-a4ef-dcb2b919cbec.mp4

**Comment by BenHenning** [comment]
How odd. I was able to repro this (I think) by fully finishing lesson 4, and then noticing it crashes. I'll need to check the logcat logs to see what the actual stacktrace is.

**Comment by BenHenning** [comment]
I see this stacktrace when reproed locally:

```
2022-04-26 15:18:42.287 4892-4892/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 4892
    java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary (463 follows :)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
        at android.text.HtmlToSpannedConverter.convert(Html.java:772)
        at android.text.Html.fromHtml(Html.java:242)
        at androidx.core.text.HtmlCompat.fromHtml(HtmlCompat.java:163)
        at org.oppia.android.util.parser.html.CustomHtmlContentHandler$Companion.fromHtml(CustomHtmlContentHandler.kt:210)
        at org.oppia.android.util.parser.html.HtmlParser.parseOppiaHtml(HtmlParser.kt:90)
        at org.oppia.android.app.player.state.StatePlayerRecyclerViewAssembler$Builder$addContentSupport$2.invoke(StatePlayerRecyclerViewAssembler_updated.kt:940)
        at org.oppia.android.app.player.state.StatePlayerRecyclerViewAssembler$Builder$addContentSupport$2.invoke(StatePlayerRecyclerViewAssembler_updated.kt:878)
        at org.oppia.android.app.recyclerview.BindableAdapter$MultiTypeBuilder$registerViewBinder$viewHolderFactory$1$1.bind$app_view_models_kt(BindableAdapter.kt:296)
        at org.oppia.android.app.recyclerview.BindableAdapter.onBindViewHolder(BindableAdapter.kt:88)
        at org.oppia.android.app.recyclerview.BindableAdapter.onBindViewHolder(BindableAdapter.kt:32)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
```

I suspect this will be fixed by #3852 since a bunch of improvements were added around paragraph handling, but it's interesting because something specific must be happening in the EndExploration card content to trigger this. I'm going to see if I can find the content HTML.

**Comment by BenHenning** [comment]
The content for this state is:

```html
<p>When the pizza was ready, Malik cut some big slices for all of them to eat.</p><p>\"This is yummy!\" said Maya.</p><p>\"Yes, this is great!\" agreed Omar. \"I\342\200\231m sure we can win the contest with your help!\"</p><oppia-noninteractive-image alt-with-value=\"&amp;quot;Omar holding up a tasty pizza&amp;quot;\" caption-with-value=\"&amp;quot;&amp;quot;\" filepath-with-value=\"&amp;quot;img_20201004_004103_sdwe5l05h3_height_263_width_294.svg&amp;quot;\"></oppia-noninteractive-image><p>Good job on completing this lesson! Now that our trio has their ingredients, they need to practice making pizza to get ready for the upcoming festival. Join us in the next lesson to find out what happens when they start to make their practice pizza, and learn more about subtracting BIG numbers!</p>
```

I can't be sure, but I suspect the issue has something to  do with the paragraph tags surrounding the interactive image. It's probably an edge case that we just haven't noticed until now. I think Veena's fix in the PR above for paragraph handling might address this, and given that it's blocking a likely topic for the upcoming study I'm going to try and fix this as part of the MR4 work.

**Comment by KolliAnitha** [comment]
Completed chapter 4 in Addition and Subtraction topic in alpha build 0.7-alpha-6c08d882d3.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
