### ISSUE TITLE
App doesn't open on every alternate tap on the icon

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4323]
**Describe the bug**
App doesn't open on every alternate tap on the icon

**To Reproduce**
1. Go to Home page
2. Tap on Oppia
3. Page blinks and app doesnt open
4. Tap on Oppia icon again 
5. App opens properly

**Expected behavior**
App should open when the user tries to open it

Actual Result:
App doesn't open and page blinks on every 1st, 3rd and 5th tap on the Oppia icon but opens on 2nd, 4th and 6th tap

https://user-images.githubusercontent.com/101634267/165509752-80500abb-6220-48d9-beb9-331870728550.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
Interesting. This looks like a crash; further investigation is needed to see if it can be reproed locally or if it's specific to @KolliAnitha's device.

**Comment by BenHenning** [comment]
Adding this tentatively to beta MR1 & assigning it to myself as it may be indicating a much worse issue that we'll want to be aware of.

**Comment by BenHenning** [comment]
@KolliAnitha can you try this on a device other than the Nord2? I'm not able to repro on my Pixel 4 or Nexus 5X (a fast and slow device, respectively), though I did see this in a video from one of our user study coordinators. It'd be nice to try and figure out the subset of affected devices so that I can successfully repro it.

Also, if you can after reproing the issue create a bug report & send it to me? I suggest not uploading it to GitHub or making it open access since bug reports will contain info about your system and installed apps. Please let me know if you have any concerns.

**Comment by BenHenning** [comment]
I haven't yet received system logs to analyze, but in developing a separate issue I encountered this issue when I intentionally kept the splash open:

```2022-07-01 18:13:58.365 21588-21588/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 21588
    java.lang.IllegalStateException: Expected to initialize the locale for the first time. If this is in a test, did you use InitializeDefaultLocaleRule?
        at org.oppia.android.app.translation.AppLanguageLocaleHandler.initializeLocale(AppLanguageLocaleHandler.kt:41)
        at org.oppia.android.app.splash.SplashActivityPresenter$subscribeToOnboardingFlow$1.onChanged(SplashActivityPresenter_updated.kt:73)
        at org.oppia.android.app.splash.SplashActivityPresenter$subscribeToOnboardingFlow$1.onChanged(SplashActivityPresenter_updated.kt:64)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.Transformations$1.onChanged(Transformations.java:76)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at org.oppia.android.util.data.DataProviders$NotifiableAsyncLiveData.setValue(DataProviders.kt:399)
        at org.oppia.android.util.data.DataProviders$NotifiableAsyncLiveData.setValue(DataProviders.kt:348)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

This is a known crash from when localization was introduced. I wonder if the situation here is that the splash screen is taking a bit to advance so tapping a second time is triggering the above crash. I'll need to see system logs to confirm, but this seems like a good guess.

**Comment by BenHenning** [comment]
I noticed the crash in my previous comment can also reproed by using the system back button from the profile screen & reopening the app. Still not clear if this is the same issue observed in the opening comment.

**Comment by KolliAnitha** [comment]
App opens properly on every tap on the icon in the beta version.
