### ISSUE TITLE
App can't be installed on SDK 31 devices

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4750]
**Describe the bug**
SDK 31 devices are currently incompatible with the app as of #4747 being merged.

**To Reproduce**
1. Build the app locally on a version of develop after #4747
2. Try to install the app on an emulator or real device running at least SDK 31 (Android 12)
3. Notice that it can't be installed, and gives the error:

```
[BT:1.8.0] Error: Installation of the app failed.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Installation of the app failed.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:155)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$2(InstallApksCommand.java:212)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:212)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
Caused by: com.android.ddmlib.InstallException: Failed to commit install session 1294565962 with command cmd package install-commit 1294565962. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1294565962.tmp/base.apk (at Binary XML file line #58): org.oppia.android.app.splash.SplashActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
	at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:99)
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
	at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1166)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:139)
```

**Expected behavior**
The app should be installable on SDK 31+ devices.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: Pixel 5 emulator
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 31
- App version (you can get this through system app settings or via the admin controls menu in-app): latest develop

**Additional context**
I can't be sure whether this will affect Play Store installs as those APKs are generated by Play Store itself, but I assume this will be a problem given the details of the error (that we're not configuring something correctly for SDK 31).

**Comment by BenHenning** [comment]
So it seems there are two issues to solve here:
1. We need to declare SplashActivity as exported per new SDK 31 rules (seems fine and is an easy fix).
2. PendingIntents need to be explicitly marked as mutable. We don't use PendingIntents directly, but WorkManager does via Jetpack's AndroidX Work package. Unfortunately, this means upgrading to a newer version of AndroidX Work which will, indirectly, cause other dependencies to update. I'm currently investigating whether this effect can be minimized to avoid too many production dependency changes (as those could impact more than just SDK 31).

**Comment by BenHenning** [comment]
So it seems that because the version of AndroidX WorkManager that I was trying to upgrade to doesn't check for Android S (SDK 31) correctly (due to it being prerelease & possibly the codename changing, but I'm not 100% certain on this), we probably do need to upgrade to a fully available released version (e.g. 2.7.0 instead of 2.7.0-alpha02 as I was trying to do per https://issuetracker.google.com/issues/180884673). Unfortunately, this leads to an upgrade to Kotlin 1.5 SDK which, if memory serves, may cause binary compatibility issues with Kotlin 1.4 (our current version). If that happens we'll need to upgrade to Kotlin 1.5 which would be extremely risky to cherry-pick without another test pass (at least high-priority tests).

My other idea was to conditionally disable work manager, but we'd need a lot of extra setup that we don't have today to conditionally initialize it (per https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration#on-demand) so I don't think this is what we'll want to do.

I'll tinker with this more tomorrow and see if I can come to a solution that minimizes risk to the beta release.

**Comment by BenHenning** [comment]
I think we're able disable WorkManager, actually, and filed #4751 to track re-enabling it. Per current Play metrics, this will affect approximately 9% of our userbase (i.e. that's how many users will have analytics disabled).

**Comment by KolliAnitha** [comment]
Able to install app in Android 12 version in One plus nord2 5G
![IMG_20221124_094849](https://user-images.githubusercontent.com/101634267/203693519-a1505aa8-372b-4af9-8573-a2394f7c4535.jpg)
![Screenshot_2022-11-24-09-47-08-android12](https://user-images.githubusercontent.com/101634267/203693523-798acc70-8a81-4f13-bdf7-608d2ddc6352.jpg)
