### ISSUE TITLE
Deprecate support for Android KitKat

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5012]
**Is your feature request related to a problem? Please describe.**

We have decided not to pursue support for Android KitKat. This was an aspirational goal that we had wanted to attempt because we knew of tablets owned by some partners that still run on KitKat, but as the years go by we expect that the number of such devices will dwindle.

Additionally, there are significant barriers to supporting KitKat, due to this requiring third-party dependencies that cannot be upgraded and have security issues. So we have decided to not attempt to support it, and remove any extra code that is special-cased for KitKat in order to simplify the codebase and development experience.

**Describe the solution you'd like**

Remove any code in the Android codebase that is there only to provide support for KitKat.

**Describe alternatives you've considered**
We could leave the KitKat code in, but this does not seem useful since we aren't planning to support it in the long run. It seems better to clean up the code in order to reduce the maintenance burden and make it easier for developers to follow it.

**Comment by theMr17** [comment]
Hi @adhiamboperes, I would like to work on this issue. My approach to solve this will be as following:

- Search the codebase for any checks for `KITKAT` and remove any unnecessary code.
- Search the codebase for any checks for `Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP` or `Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP` and modify the code accordingly.
- Upgrade the `minSdkVersion` to `21`.

Please let me know, if anything else needs to be done.

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes, I would like to work on this issue. My approach to solve this will be as following:
> 
> * Search the codebase for any checks for `KITKAT` and remove any unnecessary code.
> * Search the codebase for any checks for `Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP` or `Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP` and modify the code accordingly.
> * Upgrade the `minSdkVersion` to `21`.
> 
> Please let me know, if anything else needs to be done.

@the-mr17 I don't recommend directly working on this issue at the moment since there are blocking issues that have not been addressed, e.g when you search for existing usages of the tems you mention, you will see TODOs like #4751, which need to be fixed first.

**Comment by adhiamboperes** [comment]
We need to prioritize this issue since  https://github.com/oppia/oppia-android/pull/5437 raises  `minSdkVersion` to 21, due to

```
Error: Exception in thread "main" com.google.devtools.build.android.AndroidManifestProcessor$ManifestProcessingException: Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [@maven//:androidx_activity_activity_compose] /tmp/manifest_merge_tmp9428924506616588346/AndroidManifest17206523561529774253.xml
	Suggestion: use tools:overrideLibrary="androidx.activity.compose" to force usage
	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:186)
	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:228)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$5.call(ResourceProcessorBusyBox.java:97)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:251)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:181)
Target //:oppia_dev_kitkat failed to build
```

And https://github.com/oppia/oppia-android/issues/5442

@kkmurerwa, could you PTAL?

**Comment by BenHenning** [comment]
> We need to prioritize this issue since #5437 raises `minSdkVersion` to 21, due to
> 
> ```
> Error: Exception in thread "main" com.google.devtools.build.android.AndroidManifestProcessor$ManifestProcessingException: Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [@maven//:androidx_activity_activity_compose] /tmp/manifest_merge_tmp9428924506616588346/AndroidManifest17206523561529774253.xml
> 	Suggestion: use tools:overrideLibrary="androidx.activity.compose" to force usage
> 	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:186)
> 	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:228)
> 	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$5.call(ResourceProcessorBusyBox.java:97)
> 	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:251)
> 	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:181)
> Target //:oppia_dev_kitkat failed to build
> ```
> 
> And #5442
> 
> @kkmurerwa, could you PTAL?

@adhiamboperes what does #5442 have to do with deprecating KitKat? I read through both this and that thread and couldn't figure out the association.

**Comment by BenHenning** [comment]
Taking on this issue today since I've noticed that the CI builds are a bit slower due to extra binaries being built (including KitKat), so this seems like a relatively easy win for better CI performance on PRs.

**Comment by adhiamboperes** [comment]
> > We need to prioritize this issue since #5437 raises `minSdkVersion` to 21, due to
   
> > 
> >       
> >     
> > 
> >     
> >   
> > And #5442
> > @kkmurerwa, could you PTAL?
> 
> @adhiamboperes what does #5442 have to do with deprecating KitKat? I read through both this and that thread and couldn't figure out the association.

@BenHenning, Pending Intents are only used by WorkManager currently, and that was gated for versions below lollipop in [AbstractOppiaApplication.kt](https://github.com/oppia/oppia-android/pull/5630/files#diff-b912fb59fc5587f6eb5cbde146a1a2ed08d4b4c824ba8015512c7ef8ee4a2fc1).
