### ISSUE TITLE
[BUG]:Oppia-Android app not opening on the Android 6.0.1 Marshmello

### ISSUE THREAD

**Issue by prafulbbandre** [oppia/oppia-android#5093]
### Describe the bug

I setup the oppia android project locally and deployed the app to my android device (6.0.1) but as i open the app it closes on its own.
But the app is working fine on higher specs devices.

### Steps To Reproduce

setup oppia-android locally 
deploy the app on a abdroid 6.0.1 device

### Expected Behavior

It should work fine for the android 6.0.1 devices.

### Screenshots/Videos

https://github.com/oppia/oppia-android/assets/109658545/eb8a8781-23c1-4a33-a842-c2ed1f43369c

### Stacktrace
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 1041
    java.lang.NoClassDefFoundError: org.oppia.android.util.locale.AndroidLocaleFactory$createAndroidLocale$1
        at org.oppia.android.util.locale.AndroidLocaleFactory.createAndroidLocale(AndroidLocaleFactory.kt:59)
        at org.oppia.android.util.locale.DisplayLocaleImpl$formattingLocale$2.invoke(DisplayLocaleImpl.kt:25)
        at org.oppia.android.util.locale.DisplayLocaleImpl$formattingLocale$2.invoke(DisplayLocaleImpl.kt:17)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.oppia.android.util.locale.DisplayLocaleImpl.getFormattingLocale(DisplayLocaleImpl.kt)
        at org.oppia.android.util.locale.DisplayLocaleImpl.setAsDefault(DisplayLocaleImpl.kt:46)
        at org.oppia.android.domain.locale.LocaleController.setAsDefault(LocaleController.kt:239)
        at org.oppia.android.app.translation.ActivityLanguageLocaleHandler.initializeLocaleForActivity(ActivityLanguageLocaleHandler.kt:41)
        at org.oppia.android.app.activity.InjectableAppCompatActivity.onInitializeLocalization(InjectableAppCompatActivity.kt:77)
        at org.oppia.android.app.activity.InjectableAppCompatActivity.attachBaseContext(InjectableAppCompatActivity.kt:33)
        at android.app.Activity.attach(Activity.java:6288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2443)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5628)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

### What device/emulator are you using?

Vivo y55s

### Which Android version is your device/emulator running?

Android 6.0.1

### Which version of the Oppia Android app are you using?

App version 1.0

**Comment by Shaik-Sirajuddin** [comment]
Hi @adhiamboperes 
I would like to work on this issue.
I see this issue is due to the use of **computeIfAbsent**() method of **ConcurrentHashMap** . The method was introduced in API level 24 , which ensures atomicity across multiple threads calling into the function . But Android 6.0.1 is API level 23

Here is the exact code block of this : 
 ```
memoizedLocales.computeIfAbsent(localeContext) {
        val chooser = profileChooserSelector.findBestChooser(localeContext  )
        val primaryLocaleSource = LocaleSource.createFromPrimary(localeContext)
        val fallbackLocaleSource = LocaleSource.createFromFallback(localeContext)
        val proposal = chooser.findBestProposal(primaryLocaleSource, fallbackLocaleSource)
        return@computeIfAbsent proposal.computedLocale
      }
```
By using this method , the code ensures that the computation is only performed once  when called by multiple threads , this  is done only once by acquiring a lock internally by **computeIfAbsent** method.

To fix this issue I am thinking of using getOrPut for Api level's below 24.

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes I would like to work on this issue. I see this issue is due to the use of **computeIfAbsent**() method of **ConcurrentHashMap** . The method was introduced in API level 24 , which ensures atomicity across multiple threads calling into the function . But Android 6.0.1 is API level 23
> 
> Here is the exact code block of this :
> 
> ```
> memoizedLocales.computeIfAbsent(localeContext) {
>        val chooser = profileChooserSelector.findBestChooser(localeContext  )
>        val primaryLocaleSource = LocaleSource.createFromPrimary(localeContext)
>        val fallbackLocaleSource = LocaleSource.createFromFallback(localeContext)
>        val proposal = chooser.findBestProposal(primaryLocaleSource, fallbackLocaleSource)
>        return@computeIfAbsent proposal.computedLocale
>      }
> ```
> 
> By using this method , the code ensures that the computation is only performed once when called by multiple threads , this is done only once by acquiring a lock internally by **computeIfAbsent** method.
> 
> To fix this issue I am thinking of using getOrPut for Api level's below 24.


Can you reproduce this issue if you use an API level 23 emulator?

**Comment by Shaik-Sirajuddin** [comment]
Yes @adhiamboperes  , Was able to debug the issue by launching the app on emulator ( Android version 6.0 ) 
App crashes on launch.

**Comment by adhiamboperes** [comment]
Sure, I'm assigning the issue to you. In your PR, please include screenshot/video of before and after showing the bug and the fix as reproduced by you.

**Comment by Shaik-Sirajuddin** [comment]
Thanks , I will ensure that.

> Sure, I'm assigning the issue to you. In your PR, please include screenshot/video of before and after showing the bug and the fix as reproduced by you.

**Comment by BenHenning** [comment]
Keeping this as a 0.12 blocker for best-effort fixing, but currently M users make up just 0.7% of beta app usage.

Edit: It occurred to me that this might be a lower-than-correct representation since the app not being able to open will significantly de-bias data.

**Comment by seanlip** [comment]
Following up from an earlier discussion with @BenHenning -- just confirming that the 1-star feedback we got on the beta version a couple of weeks ago, saying that "the application does not open", is indeed correlated to Marshmallow (Android 6.0, SDK 23).

**Comment by BenHenning** [comment]
NB we decided to finalize the 0.12 release and release a new 0.13 rather than hotfix 0.12 (since it's now been out for a month).
