### ISSUE TITLE
[BUG]: GitHub CI Checks are failing due to timeout 

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#5140]
### Describe the bug

Mostly Bazel tests (Robolectric) are failing in GitHub PR CI checks.

#### [Here](https://gist.github.com/MohitGupta121/df1b44fc767f0dd10afb2c874586e7c7#file-run-bazel-test) is the full Raw log of checks.

These are some sample logs from failing checks:
```
"Thread-95" Id=881 TIMED_WAITING
	at java.base@9.0.7.1/java.lang.Thread.sleep(Native Method)
	at android.net.TetheringManager.lambda$startPollingForConnector$1(TetheringManager.java:286)
	at android.net.TetheringManager$$Lambda$224/288120411.run(Unknown Source)
	at java.base@9.0.7.1/java.lang.Thread.run(Thread.java:844)

"pool-569-thread-4" Id=879 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@17b0792
	at java.base@9.0.7.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@17b0792
	at java.base@9.0.7.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@9.0.7.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2062)
	at java.base@9.0.7.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.base@9.0.7.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.base@9.0.7.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.base@9.0.7.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base@9.0.7.1/java.lang.Thread.run(Thread.java:844)
```

This PR is facing this PR: https://github.com/oppia/oppia-android/pull/5131
Also this PR #5139 face same issue but after run-running the test passed.

### Steps To Reproduce

N/A

### Expected Behavior

Tests should be passed or give specific failure.

**Comment by Sandesh282** [comment]
## Technical Breakdown

Robolectric tests on CI intermittently hang forever. The stack traces show `TetheringManager` spinning a background polling thread that never exits, keeping the JVM alive past the GitHub Actions job timeout. Tests that re-run locally pass, indicating a flaky non-terminating background thread rather than a logical failure.

- **Part 1: Identify the triggering test targets**

  **What to do:**
  - a. Search for test targets that use any networking/connectivity APIs: `grep -r "TetheringManager\|ConnectivityManager" app/src/test --include="*.kt"`.
  - b. Cross-reference with the CI shard that times out (shard 4 in the linked logs) to narrow down the specific `kt_android_local_test` target.

- **Part 2: Add a Robolectric shadow to suppress the background thread**

  **What to do:**
  - a. In `testing/src/main/java/org/oppia/android/testing/robolectric/`, create `ShadowTetheringManager.kt` that extends Robolectric's shadow system and overrides `startPollingForConnector` to be a no-op.
  - b. Annotate the shadow with `@Implements(TetheringManager::class)`.
  - c. Register it via `@Config(shadows = [ShadowTetheringManager::class])` on the affected test class, or globally in `OppiaRobolectricTestRunner`.

- **Part 3: Add a BUILD target and wire the shadow**

  **What to do:**
  - a. In `testing/src/main/java/org/oppia/android/testing/robolectric/BUILD.bazel`, add a new `kt_jvm_library` target for `ShadowTetheringManager`.
  - b. Add this target as a `dep` to the `oppia_robolectric_test_runner` library so it applies globally.

**Comment by adhiamboperes** [comment]
@Sandesh282, this specific issue was filed in 2023. I think the correct approach here would be to explore:
1. Can this still be reproed? If yes, what are the steps?
2. Can a root-cause analysis be done based on the raw logs linked in the issue body?
3. From the logs, did the tests run and pass before the thread timed out, or did the timeout prevent the tests from running?

**Comment by Sandesh282** [comment]
> [@Sandesh282](https://github.com/Sandesh282), this specific issue was filed in 2023. I think the correct approach here would be to explore:
> 
> 1. Can this still be reproed? If yes, what are the steps?
> 2. Can a root-cause analysis be done based on the raw logs linked in the issue body?
> 3. From the logs, did the tests run and pass before the thread timed out, or did the timeout prevent the tests from running?

From the raw logs:
1. The stack trace points to TetheringManager.startPollingForConnector (Android API 30+). Whether this still reproduces depends on the Robolectric version and Android SDK version currently in use. Given the issue is from 2023 and several Robolectric upgrades have happened since, the first step is to re-run the affected shard locally and see if it hangs.

2. Yes, the stack trace is conclusive. Thread-95 is in TIMED_WAITING inside Thread.sleep, called from TetheringManager.lambda$startPollingForConnector$1. This is a background polling thread that Robolectric doesn't automatically suppress. Since it's not marked as a daemon thread, it blocks JVM shutdown indefinitely after tests finish.

3. Yes, Thread-95 being in TIMED_WAITING (not RUNNABLE) and the pool threads being in WAITING on a LinkedBlockingQueue strongly indicates the test framework had already finished execution. The JVM was trying to shut down but this non-daemon thread prevented it. The timeout is a shutdown hang, not a test execution hang — the tests themselves likely completed normally.

**Comment by adhiamboperes** [comment]
> > [@Sandesh282](https://github.com/Sandesh282), this specific issue was filed in 2023. I think the correct approach here would be to explore:
> > 
> > 1. Can this still be reproed? If yes, what are the steps?
> > 2. Can a root-cause analysis be done based on the raw logs linked in the issue body?
> > 3. From the logs, did the tests run and pass before the thread timed out, or did the timeout prevent the tests from running?
> 
> From the raw logs:
> 
> 1. The stack trace points to TetheringManager.startPollingForConnector (Android API 30+). Whether this still reproduces depends on the Robolectric version and Android SDK version currently in use. Given the issue is from 2023 and several Robolectric upgrades have happened since, the first step is to re-run the affected shard locally and see if it hangs.

Our robolectric version can be found in third_party/versions.bzl

**Comment by adhiamboperes** [comment]
This issue still has `work: medium` label because the path to solution is still not clear.

**Comment by Sandesh282** [comment]
> > > [@Sandesh282](https://github.com/Sandesh282), this specific issue was filed in 2023. I think the correct approach here would be to explore:
> > > 
> > > 1. Can this still be reproed? If yes, what are the steps?
> > > 2. Can a root-cause analysis be done based on the raw logs linked in the issue body?
> > > 3. From the logs, did the tests run and pass before the thread timed out, or did the timeout prevent the tests from running?
> > 
> > 
> > From the raw logs:
> > 
> > 1. The stack trace points to TetheringManager.startPollingForConnector (Android API 30+). Whether this still reproduces depends on the Robolectric version and Android SDK version currently in use. Given the issue is from 2023 and several Robolectric upgrades have happened since, the first step is to re-run the affected shard locally and see if it hangs.
> 
> Our robolectric version can be found in third_party/versions.bzl

We're currently on Robolectric 4.7 (`org.robolectric:robolectric: "4.7"` in `third_party/versions.bzl`). Robolectric 4.7 does not include a built-in `ShadowTetheringManager` that suppresses `startPollingForConnector`, so the non-daemon thread issue is still theoretically present for tests running on API 30+. The question of "can it still be reproduced" depends on which SDK level the affected shard runs under so if CI has since moved to a lower API level for those tests, the issue may have silently stopped triggering.

**Comment by Sandesh282** [comment]
> This issue still has `work: medium` label because the path to solution is still not clear.

Based on the log analysis, the tests themselves complete successfully, the timeout is a JVM shutdown hang, not a test execution hang. That actually narrows the path considerably: the fix doesn't require changing any test logic, only ensuring the TetheringManager polling thread either doesn't start or is a daemon thread in the Robolectric environment. Two concrete options:

1. Upgrade Robolectric — later versions (4.9+) added more complete SDK 31+ shadows. If an upgrade is feasible, it's worth checking whether it silently resolves this.
2. Custom shadow — write a ShadowTetheringManager that stubs startPollingForConnector as a no-op and registers it globally in OppiaRobolectricTestRunner.

Option 2 is a targeted, low-risk fix regardless of Robolectric version. Would it be acceptable to proceed with that approach?

**Comment by adhiamboperes** [comment]
I think we should investigate if a newer, compatible version of Robolectric has the shadow we need, before falling back to writing a custom shadow.

**Comment by Sandesh282** [comment]
@adhiamboperes There's no ShadowTetheringManager in Robolectric (any version) -- this is real framework code executing via the android-all jar, not a shadow. So the question isn't whether a newer Robolectric version has the shadow, but whether a newer android-all SDK jar for API 30/31 handles startPollingForConnector differently (e.g. exits cleanly in a non-production JVM environment).

We're currently on Robolectric 4.7 (released ~2022). The fastest way to test your suggestion is to bump to the latest (4.13.x) and run the affected shard. If the hang disappears, great. If it doesn't, the custom ShadowTetheringManager is the only option left. Hopefully whoever picks this up can start from there.
