### ISSUE TITLE
[BUG]: Instrumentation tests fail to build

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5334]
### Describe the bug

Instrumentation tests are currently failing to build in Bazel. Specifically, the ``//instrumentation:oppia_test`` build is failing with the following error:

```sh
bazel build //instrumentation:oppia_test 
INFO: Invocation ID: 2851d5ff-4cc5-48f3-bb58-e10b3b1d6ab9
INFO: Analyzed target //instrumentation:oppia_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/bhenning/.cache/bazel/_bazel_bhenning/786e1e39b1d54d329507f45978f9977a/external/maven/BUILD:5935:11: Desugaring external/maven/v1/https/repo1.maven.org/maven2/org/robolectric/junit/4.5/junit-4.5.jar for Android failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log snippet, file at /usr/local/google/home/bhenning/.cache/bazel/_bazel_bhenning/786e1e39b1d54d329507f45978f9977a/bazel-workers/worker-50-Desugar.log ---8<---8<---
[... truncated ...]
vtools.build.android.desugar.DefaultMethodClassFixer.stubMissingDefaultAndBridgeMethods(DefaultMethodClassFixer.java:304)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.stubMissingDefaultAndBridgeMethods(DefaultMethodClassFixer.java:283)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:170)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:127)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:153)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
        at com.google.devtools.build.android.desugar.nest.NestDesugaring.visitEnd(NestDesugaring.java:171)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:549)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:246)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1019)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:979)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:957)

Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/runners/model/Statement
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:67)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.loadFromInternal(LambdaDesugaring.java:337)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.access$500(LambdaDesugaring.java:56)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.createLookup(LambdaDesugaring.java:617)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:402)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:549)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:246)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1019)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:979)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:957)
Caused by: java.lang.ClassNotFoundException: Class org.junit.runners.model.Statement not found
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 23 more
---8<---8<--- End of log snippet, 11495 chars omitted ---8<---8<---
Target //instrumentation:oppia_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

### Steps To Reproduce

Check out the latest develop (604b609e1fd7dc18519da60c8434bb6e9fec60a5) and try to build: ``bazel build //instrumentation:oppia_test``.

### Expected Behavior

Instrumentation tests should build successfully.

### What device/emulator are you using?

N/A

### Which Android version is your device/emulator running?

N/A

### Which version of the Oppia Android app are you using?

N/A

**Comment by BenHenning** [comment]
From a ``git bisect`` investigation, it seems this was introduced in 164f33b86bec3dcaab6a3f39d15f6be82a4a28f8 via #5098.

From that PR, it seems extremely likely the issue was introduced from this line: https://github.com/oppia/oppia-android/pull/5098/files#diff-b39b7c940cf9f44a11a5f82a5395e85f4f08cbf5117a9d8df38b267a3a64bf76R28. This makes sense since ``//testing`` would pull in Robolectric (which is the Maven target failing to be desugared) which has desugar issues (https://github.com/bazelbuild/bazel/issues/13684 is a related issue I've seen before that's likely caused by the same root problem with our use of an old dexer).

Given how large #5098 is, I think I'm going to opt for a fix-forward since the regression is fully isolated to ``//testing``.

**Comment by adhiamboperes** [comment]
@BenHenning, the line linked in you comment above doesn't actually load to the expected line when url is clicked. Could you link it on develop?

**Comment by adhiamboperes** [comment]
This does build on CI? could it be related to your OS?

**Comment by BenHenning** [comment]
@adhiamboperes we don't build instrumentation tests on CI which is why this was missed originally. While I'm only using Linux, it fails on both of my workstations that I tried setting it up on, and in CI when updated to include the builds (see #5335).
