### ISSUE TITLE
[BUG]: java.lang.SecurityException - Not allowed to start service Intent

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5554]
### Describe the bug

This crash is trending on Firebase and has 142 events affecting 2 users at time of writing. 

Stacktrace is as follows:

``` 
Fatal Exception: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1250)
       at android.app.ContextImpl.startService(ContextImpl.java:1227)
       at android.content.ContextWrapper.startService(ContextWrapper.java:581)
       at com.google.firebase.iid.w.c(SourceFile:131)
       at com.google.firebase.iid.w.b(SourceFile:92)
       at com.google.firebase.iid.w.a(SourceFile:91)
       at com.google.firebase.iid.af.a(SourceFile:73)
       at com.google.firebase.iid.ae.run(SourceFile)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at bf.b.run(SourceFile:2)
       at java.lang.Thread.run(Thread.java:818)
```

### Steps To Reproduce

Not sure, this is a crash that Firebase is reporting as trending.

### Expected Behavior

The crash should not occur.

### What device/emulator are you using?

The devices are Lenovo Mobile (75%, Android 6) and Atouch (25%, Android 10, rooted).

### Which Android version is your device/emulator running?

Android 6 and Android 10

### Which version of the Oppia Android app are you using?

0.13-beta-dcde7b359e (154)

**Comment by adhiamboperes** [comment]
Will likely be fixed by updating the versions of the Firebase libraries. When I added Firebase libs aside from the existing analytics and crashlytics, I used the lowest supported one on Bazel 4 which were pretty old.

**Comment by aadityaverma2011** [comment]
would like to work on this issue . Please assign this to me
