### ISSUE TITLE
Crash on Profile edit page landscape.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#989]
Change profile image in portrait mode, now change orientation and click on edit image.

Error

```
2020-06-30 14:07:46.658 10505-10505/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 10505
    java.lang.IllegalStateException: FragmentManager has been destroyed
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1911)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1942)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:212)
        at org.oppia.app.profileprogress.ProfileProgressActivityPresenter.showPictureEditDialog(ProfileProgressActivityPresenter.kt:63)
        at org.oppia.app.profileprogress.ProfileProgressActivity.onProfilePictureClicked(ProfileProgressActivity.kt:72)
        at org.oppia.app.profileprogress.ProfileProgressHeaderViewModel.clickOnProfilePicture(ProfileProgressHeaderViewModel.kt:44)
        at org.oppia.app.databinding.ProfileProgressHeaderBindingLandImpl._internalCallbackOnClick(ProfileProgressHeaderBindingLandImpl.java:412)
        at org.oppia.app.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
```

**Comment by BenHenning** [comment]
Confirming this is fixed on the release branch.
